// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThormaBackendAPI.Data;

#nullable disable

namespace ThormaBackendAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308142829_AddLogsTable")]
    partial class AddLogsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ThormaBackendAPI.Models.Festo", b =>
                {
                    b.Property<int>("Azon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Meghalt")
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Szuletett")
                        .HasColumnType("int");

                    b.HasKey("Azon");

                    b.ToTable("festok");
                });

            modelBuilder.Entity("ThormaBackendAPI.Models.Kep", b =>
                {
                    b.Property<string>("Leltar")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Anyag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Fazon")
                        .HasColumnType("int");

                    b.Property<int>("Keszult")
                        .HasColumnType("int");

                    b.Property<decimal>("Magas")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("Szeles")
                        .HasColumnType("decimal(5,1)");

                    b.Property<string>("Technika")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Leltar");

                    b.HasIndex("Fazon");

                    b.ToTable("kepek");
                });

            modelBuilder.Entity("ThormaBackendAPI.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsAuthFailure")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("logs");
                });

            modelBuilder.Entity("ThormaBackendAPI.Models.Kep", b =>
                {
                    b.HasOne("ThormaBackendAPI.Models.Festo", "Festo")
                        .WithMany("Kepek")
                        .HasForeignKey("Fazon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festo");
                });

            modelBuilder.Entity("ThormaBackendAPI.Models.Festo", b =>
                {
                    b.Navigation("Kepek");
                });
#pragma warning restore 612, 618
        }
    }
}
